//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftFin.Sefaz.srwsNFeConsulta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeConsultaProtocolo4", ConfigurationName="srwsNFeConsulta.NFeConsultaProtocolo4Soap12")]
    public interface NFeConsultaProtocolo4Soap12 {
        
        // CODEGEN: Generating message contract since the operation nfeConsultaNF is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeConsultaProtocolo4/nfeConsultaNF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoftFin.Sefaz.srwsNFeConsulta.nfeConsultaNFResponse nfeConsultaNF(SoftFin.Sefaz.srwsNFeConsulta.nfeConsultaNFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeConsultaProtocolo4/nfeConsultaNF", ReplyAction="*")]
        System.Threading.Tasks.Task<SoftFin.Sefaz.srwsNFeConsulta.nfeConsultaNFResponse> nfeConsultaNFAsync(SoftFin.Sefaz.srwsNFeConsulta.nfeConsultaNFRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeConsultaNFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeConsultaProtocolo4", Order=0)]
        public System.Xml.XmlNode nfeDadosMsg;
        
        public nfeConsultaNFRequest() {
        }
        
        public nfeConsultaNFRequest(System.Xml.XmlNode nfeDadosMsg) {
            this.nfeDadosMsg = nfeDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeConsultaNFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeConsultaProtocolo4", Order=0)]
        public System.Xml.XmlNode nfeResultMsg;
        
        public nfeConsultaNFResponse() {
        }
        
        public nfeConsultaNFResponse(System.Xml.XmlNode nfeResultMsg) {
            this.nfeResultMsg = nfeResultMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NFeConsultaProtocolo4Soap12Channel : SoftFin.Sefaz.srwsNFeConsulta.NFeConsultaProtocolo4Soap12, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NFeConsultaProtocolo4Soap12Client : System.ServiceModel.ClientBase<SoftFin.Sefaz.srwsNFeConsulta.NFeConsultaProtocolo4Soap12>, SoftFin.Sefaz.srwsNFeConsulta.NFeConsultaProtocolo4Soap12 {
        
        public NFeConsultaProtocolo4Soap12Client() {
        }
        
        public NFeConsultaProtocolo4Soap12Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NFeConsultaProtocolo4Soap12Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeConsultaProtocolo4Soap12Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeConsultaProtocolo4Soap12Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftFin.Sefaz.srwsNFeConsulta.nfeConsultaNFResponse SoftFin.Sefaz.srwsNFeConsulta.NFeConsultaProtocolo4Soap12.nfeConsultaNF(SoftFin.Sefaz.srwsNFeConsulta.nfeConsultaNFRequest request) {
            return base.Channel.nfeConsultaNF(request);
        }
        
        public System.Xml.XmlNode nfeConsultaNF(System.Xml.XmlNode nfeDadosMsg) {
            SoftFin.Sefaz.srwsNFeConsulta.nfeConsultaNFRequest inValue = new SoftFin.Sefaz.srwsNFeConsulta.nfeConsultaNFRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            SoftFin.Sefaz.srwsNFeConsulta.nfeConsultaNFResponse retVal = ((SoftFin.Sefaz.srwsNFeConsulta.NFeConsultaProtocolo4Soap12)(this)).nfeConsultaNF(inValue);
            return retVal.nfeResultMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftFin.Sefaz.srwsNFeConsulta.nfeConsultaNFResponse> SoftFin.Sefaz.srwsNFeConsulta.NFeConsultaProtocolo4Soap12.nfeConsultaNFAsync(SoftFin.Sefaz.srwsNFeConsulta.nfeConsultaNFRequest request) {
            return base.Channel.nfeConsultaNFAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftFin.Sefaz.srwsNFeConsulta.nfeConsultaNFResponse> nfeConsultaNFAsync(System.Xml.XmlNode nfeDadosMsg) {
            SoftFin.Sefaz.srwsNFeConsulta.nfeConsultaNFRequest inValue = new SoftFin.Sefaz.srwsNFeConsulta.nfeConsultaNFRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            return ((SoftFin.Sefaz.srwsNFeConsulta.NFeConsultaProtocolo4Soap12)(this)).nfeConsultaNFAsync(inValue);
        }
    }
}
