//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftFin.Sefaz.srwsNFeConsultaDestinatario {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4", ConfigurationName="srwsNFeConsultaDestinatario.CadConsultaCadastro4Soap12")]
    public interface CadConsultaCadastro4Soap12 {
        
        // CODEGEN: Generating message contract since the operation consultaCadastro is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4/consultaCadastro", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoftFin.Sefaz.srwsNFeConsultaDestinatario.consultaCadastroResponse consultaCadastro(SoftFin.Sefaz.srwsNFeConsultaDestinatario.consultaCadastroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4/consultaCadastro", ReplyAction="*")]
        System.Threading.Tasks.Task<SoftFin.Sefaz.srwsNFeConsultaDestinatario.consultaCadastroResponse> consultaCadastroAsync(SoftFin.Sefaz.srwsNFeConsultaDestinatario.consultaCadastroRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaCadastroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4", Order=0)]
        public System.Xml.XmlNode nfeDadosMsg;
        
        public consultaCadastroRequest() {
        }
        
        public consultaCadastroRequest(System.Xml.XmlNode nfeDadosMsg) {
            this.nfeDadosMsg = nfeDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaCadastroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/CadConsultaCadastro4", Order=0)]
        public System.Xml.XmlNode nfeResultMsg;
        
        public consultaCadastroResponse() {
        }
        
        public consultaCadastroResponse(System.Xml.XmlNode nfeResultMsg) {
            this.nfeResultMsg = nfeResultMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CadConsultaCadastro4Soap12Channel : SoftFin.Sefaz.srwsNFeConsultaDestinatario.CadConsultaCadastro4Soap12, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CadConsultaCadastro4Soap12Client : System.ServiceModel.ClientBase<SoftFin.Sefaz.srwsNFeConsultaDestinatario.CadConsultaCadastro4Soap12>, SoftFin.Sefaz.srwsNFeConsultaDestinatario.CadConsultaCadastro4Soap12 {
        
        public CadConsultaCadastro4Soap12Client() {
        }
        
        public CadConsultaCadastro4Soap12Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CadConsultaCadastro4Soap12Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CadConsultaCadastro4Soap12Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CadConsultaCadastro4Soap12Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftFin.Sefaz.srwsNFeConsultaDestinatario.consultaCadastroResponse SoftFin.Sefaz.srwsNFeConsultaDestinatario.CadConsultaCadastro4Soap12.consultaCadastro(SoftFin.Sefaz.srwsNFeConsultaDestinatario.consultaCadastroRequest request) {
            return base.Channel.consultaCadastro(request);
        }
        
        public System.Xml.XmlNode consultaCadastro(System.Xml.XmlNode nfeDadosMsg) {
            SoftFin.Sefaz.srwsNFeConsultaDestinatario.consultaCadastroRequest inValue = new SoftFin.Sefaz.srwsNFeConsultaDestinatario.consultaCadastroRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            SoftFin.Sefaz.srwsNFeConsultaDestinatario.consultaCadastroResponse retVal = ((SoftFin.Sefaz.srwsNFeConsultaDestinatario.CadConsultaCadastro4Soap12)(this)).consultaCadastro(inValue);
            return retVal.nfeResultMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftFin.Sefaz.srwsNFeConsultaDestinatario.consultaCadastroResponse> SoftFin.Sefaz.srwsNFeConsultaDestinatario.CadConsultaCadastro4Soap12.consultaCadastroAsync(SoftFin.Sefaz.srwsNFeConsultaDestinatario.consultaCadastroRequest request) {
            return base.Channel.consultaCadastroAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftFin.Sefaz.srwsNFeConsultaDestinatario.consultaCadastroResponse> consultaCadastroAsync(System.Xml.XmlNode nfeDadosMsg) {
            SoftFin.Sefaz.srwsNFeConsultaDestinatario.consultaCadastroRequest inValue = new SoftFin.Sefaz.srwsNFeConsultaDestinatario.consultaCadastroRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            return ((SoftFin.Sefaz.srwsNFeConsultaDestinatario.CadConsultaCadastro4Soap12)(this)).consultaCadastroAsync(inValue);
        }
    }
}
