// <auto-generated />
namespace SoftFin.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20181015Ricardo01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20181015Ricardo01));
        
        string IMigrationMetadata.Id
        {
            get { return "201810151516096_20181015Ricardo01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
