//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftFin.Sefaz.srwsNFeInutilizacao {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeInutilizacao4", ConfigurationName="srwsNFeInutilizacao.NFeInutilizacao4Soap12")]
    public interface NFeInutilizacao4Soap12 {
        
        // CODEGEN: Generating message contract since the operation nfeInutilizacaoNF is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeInutilizacao4/nfeInutilizacaoNF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoftFin.Sefaz.srwsNFeInutilizacao.nfeInutilizacaoNFResponse nfeInutilizacaoNF(SoftFin.Sefaz.srwsNFeInutilizacao.nfeInutilizacaoNFRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeInutilizacao4/nfeInutilizacaoNF", ReplyAction="*")]
        System.Threading.Tasks.Task<SoftFin.Sefaz.srwsNFeInutilizacao.nfeInutilizacaoNFResponse> nfeInutilizacaoNFAsync(SoftFin.Sefaz.srwsNFeInutilizacao.nfeInutilizacaoNFRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeInutilizacaoNFRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeInutilizacao4", Order=0)]
        public System.Xml.XmlNode nfeDadosMsg;
        
        public nfeInutilizacaoNFRequest() {
        }
        
        public nfeInutilizacaoNFRequest(System.Xml.XmlNode nfeDadosMsg) {
            this.nfeDadosMsg = nfeDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeInutilizacaoNFResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeInutilizacao4", Order=0)]
        public System.Xml.XmlNode nfeResultMsg;
        
        public nfeInutilizacaoNFResponse() {
        }
        
        public nfeInutilizacaoNFResponse(System.Xml.XmlNode nfeResultMsg) {
            this.nfeResultMsg = nfeResultMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NFeInutilizacao4Soap12Channel : SoftFin.Sefaz.srwsNFeInutilizacao.NFeInutilizacao4Soap12, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NFeInutilizacao4Soap12Client : System.ServiceModel.ClientBase<SoftFin.Sefaz.srwsNFeInutilizacao.NFeInutilizacao4Soap12>, SoftFin.Sefaz.srwsNFeInutilizacao.NFeInutilizacao4Soap12 {
        
        public NFeInutilizacao4Soap12Client() {
        }
        
        public NFeInutilizacao4Soap12Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NFeInutilizacao4Soap12Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeInutilizacao4Soap12Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeInutilizacao4Soap12Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftFin.Sefaz.srwsNFeInutilizacao.nfeInutilizacaoNFResponse SoftFin.Sefaz.srwsNFeInutilizacao.NFeInutilizacao4Soap12.nfeInutilizacaoNF(SoftFin.Sefaz.srwsNFeInutilizacao.nfeInutilizacaoNFRequest request) {
            return base.Channel.nfeInutilizacaoNF(request);
        }
        
        public System.Xml.XmlNode nfeInutilizacaoNF(System.Xml.XmlNode nfeDadosMsg) {
            SoftFin.Sefaz.srwsNFeInutilizacao.nfeInutilizacaoNFRequest inValue = new SoftFin.Sefaz.srwsNFeInutilizacao.nfeInutilizacaoNFRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            SoftFin.Sefaz.srwsNFeInutilizacao.nfeInutilizacaoNFResponse retVal = ((SoftFin.Sefaz.srwsNFeInutilizacao.NFeInutilizacao4Soap12)(this)).nfeInutilizacaoNF(inValue);
            return retVal.nfeResultMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftFin.Sefaz.srwsNFeInutilizacao.nfeInutilizacaoNFResponse> SoftFin.Sefaz.srwsNFeInutilizacao.NFeInutilizacao4Soap12.nfeInutilizacaoNFAsync(SoftFin.Sefaz.srwsNFeInutilizacao.nfeInutilizacaoNFRequest request) {
            return base.Channel.nfeInutilizacaoNFAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftFin.Sefaz.srwsNFeInutilizacao.nfeInutilizacaoNFResponse> nfeInutilizacaoNFAsync(System.Xml.XmlNode nfeDadosMsg) {
            SoftFin.Sefaz.srwsNFeInutilizacao.nfeInutilizacaoNFRequest inValue = new SoftFin.Sefaz.srwsNFeInutilizacao.nfeInutilizacaoNFRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            return ((SoftFin.Sefaz.srwsNFeInutilizacao.NFeInutilizacao4Soap12)(this)).nfeInutilizacaoNFAsync(inValue);
        }
    }
}
