// <auto-generated />
namespace SoftFin.POC.ConforLab.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Full02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Full02));
        
        string IMigrationMetadata.Id
        {
            get { return "201802191926346_Full02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
