//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe", ConfigurationName="NFePrefSP.LoteNFeSoap")]
    public interface LoteNFeSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/envioRPS", ReplyAction="*")]
        SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.EnvioRPSResponse EnvioRPS(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.EnvioRPSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/envioLoteRPS", ReplyAction="*")]
        SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.EnvioLoteRPSResponse EnvioLoteRPS(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.EnvioLoteRPSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/testeenvio", ReplyAction="*")]
        SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.TesteEnvioLoteRPSResponse TesteEnvioLoteRPS(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.TesteEnvioLoteRPSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/cancelamentoNFe", ReplyAction="*")]
        SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.CancelamentoNFeResponse CancelamentoNFe(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.CancelamentoNFeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFe", ReplyAction="*")]
        SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaNFeResponse ConsultaNFe(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaNFeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFeRecebidas", ReplyAction="*")]
        SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaNFeRecebidasResponse ConsultaNFeRecebidas(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaNFeRecebidasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaNFeEmitidas", ReplyAction="*")]
        SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaNFeEmitidasResponse ConsultaNFeEmitidas(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaNFeEmitidasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaLote", ReplyAction="*")]
        SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaLoteResponse ConsultaLote(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaInformacoesLote", ReplyAction="*")]
        SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaInformacoesLoteResponse ConsultaInformacoesLote(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaInformacoesLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.prefeitura.sp.gov.br/nfe/ws/consultaCNPJ", ReplyAction="*")]
        SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaCNPJResponse ConsultaCNPJ(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaCNPJRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnvioRPSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnvioRPSRequest", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.EnvioRPSRequestBody Body;
        
        public EnvioRPSRequest() {
        }
        
        public EnvioRPSRequest(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.EnvioRPSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class EnvioRPSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int VersaoSchema;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MensagemXML;
        
        public EnvioRPSRequestBody() {
        }
        
        public EnvioRPSRequestBody(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnvioRPSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnvioRPSResponse", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.EnvioRPSResponseBody Body;
        
        public EnvioRPSResponse() {
        }
        
        public EnvioRPSResponse(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.EnvioRPSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class EnvioRPSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetornoXML;
        
        public EnvioRPSResponseBody() {
        }
        
        public EnvioRPSResponseBody(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnvioLoteRPSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnvioLoteRPSRequest", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.EnvioLoteRPSRequestBody Body;
        
        public EnvioLoteRPSRequest() {
        }
        
        public EnvioLoteRPSRequest(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.EnvioLoteRPSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class EnvioLoteRPSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int VersaoSchema;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MensagemXML;
        
        public EnvioLoteRPSRequestBody() {
        }
        
        public EnvioLoteRPSRequestBody(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnvioLoteRPSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnvioLoteRPSResponse", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.EnvioLoteRPSResponseBody Body;
        
        public EnvioLoteRPSResponse() {
        }
        
        public EnvioLoteRPSResponse(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.EnvioLoteRPSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class EnvioLoteRPSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetornoXML;
        
        public EnvioLoteRPSResponseBody() {
        }
        
        public EnvioLoteRPSResponseBody(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TesteEnvioLoteRPSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TesteEnvioLoteRPSRequest", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.TesteEnvioLoteRPSRequestBody Body;
        
        public TesteEnvioLoteRPSRequest() {
        }
        
        public TesteEnvioLoteRPSRequest(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.TesteEnvioLoteRPSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class TesteEnvioLoteRPSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int VersaoSchema;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MensagemXML;
        
        public TesteEnvioLoteRPSRequestBody() {
        }
        
        public TesteEnvioLoteRPSRequestBody(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TesteEnvioLoteRPSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TesteEnvioLoteRPSResponse", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.TesteEnvioLoteRPSResponseBody Body;
        
        public TesteEnvioLoteRPSResponse() {
        }
        
        public TesteEnvioLoteRPSResponse(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.TesteEnvioLoteRPSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class TesteEnvioLoteRPSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetornoXML;
        
        public TesteEnvioLoteRPSResponseBody() {
        }
        
        public TesteEnvioLoteRPSResponseBody(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelamentoNFeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelamentoNFeRequest", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.CancelamentoNFeRequestBody Body;
        
        public CancelamentoNFeRequest() {
        }
        
        public CancelamentoNFeRequest(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.CancelamentoNFeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class CancelamentoNFeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int VersaoSchema;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MensagemXML;
        
        public CancelamentoNFeRequestBody() {
        }
        
        public CancelamentoNFeRequestBody(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelamentoNFeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelamentoNFeResponse", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.CancelamentoNFeResponseBody Body;
        
        public CancelamentoNFeResponse() {
        }
        
        public CancelamentoNFeResponse(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.CancelamentoNFeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class CancelamentoNFeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetornoXML;
        
        public CancelamentoNFeResponseBody() {
        }
        
        public CancelamentoNFeResponseBody(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaNFeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaNFeRequest", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaNFeRequestBody Body;
        
        public ConsultaNFeRequest() {
        }
        
        public ConsultaNFeRequest(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaNFeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class ConsultaNFeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int VersaoSchema;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MensagemXML;
        
        public ConsultaNFeRequestBody() {
        }
        
        public ConsultaNFeRequestBody(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaNFeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaNFeResponse", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaNFeResponseBody Body;
        
        public ConsultaNFeResponse() {
        }
        
        public ConsultaNFeResponse(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaNFeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class ConsultaNFeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetornoXML;
        
        public ConsultaNFeResponseBody() {
        }
        
        public ConsultaNFeResponseBody(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaNFeRecebidasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaNFeRecebidasRequest", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaNFeRecebidasRequestBody Body;
        
        public ConsultaNFeRecebidasRequest() {
        }
        
        public ConsultaNFeRecebidasRequest(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaNFeRecebidasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class ConsultaNFeRecebidasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int VersaoSchema;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MensagemXML;
        
        public ConsultaNFeRecebidasRequestBody() {
        }
        
        public ConsultaNFeRecebidasRequestBody(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaNFeRecebidasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaNFeRecebidasResponse", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaNFeRecebidasResponseBody Body;
        
        public ConsultaNFeRecebidasResponse() {
        }
        
        public ConsultaNFeRecebidasResponse(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaNFeRecebidasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class ConsultaNFeRecebidasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetornoXML;
        
        public ConsultaNFeRecebidasResponseBody() {
        }
        
        public ConsultaNFeRecebidasResponseBody(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaNFeEmitidasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaNFeEmitidasRequest", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaNFeEmitidasRequestBody Body;
        
        public ConsultaNFeEmitidasRequest() {
        }
        
        public ConsultaNFeEmitidasRequest(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaNFeEmitidasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class ConsultaNFeEmitidasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int VersaoSchema;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MensagemXML;
        
        public ConsultaNFeEmitidasRequestBody() {
        }
        
        public ConsultaNFeEmitidasRequestBody(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaNFeEmitidasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaNFeEmitidasResponse", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaNFeEmitidasResponseBody Body;
        
        public ConsultaNFeEmitidasResponse() {
        }
        
        public ConsultaNFeEmitidasResponse(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaNFeEmitidasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class ConsultaNFeEmitidasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetornoXML;
        
        public ConsultaNFeEmitidasResponseBody() {
        }
        
        public ConsultaNFeEmitidasResponseBody(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaLoteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaLoteRequest", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaLoteRequestBody Body;
        
        public ConsultaLoteRequest() {
        }
        
        public ConsultaLoteRequest(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaLoteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class ConsultaLoteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int VersaoSchema;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MensagemXML;
        
        public ConsultaLoteRequestBody() {
        }
        
        public ConsultaLoteRequestBody(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaLoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaLoteResponse", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaLoteResponseBody Body;
        
        public ConsultaLoteResponse() {
        }
        
        public ConsultaLoteResponse(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaLoteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class ConsultaLoteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetornoXML;
        
        public ConsultaLoteResponseBody() {
        }
        
        public ConsultaLoteResponseBody(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaInformacoesLoteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaInformacoesLoteRequest", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaInformacoesLoteRequestBody Body;
        
        public ConsultaInformacoesLoteRequest() {
        }
        
        public ConsultaInformacoesLoteRequest(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaInformacoesLoteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class ConsultaInformacoesLoteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int VersaoSchema;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MensagemXML;
        
        public ConsultaInformacoesLoteRequestBody() {
        }
        
        public ConsultaInformacoesLoteRequestBody(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaInformacoesLoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaInformacoesLoteResponse", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaInformacoesLoteResponseBody Body;
        
        public ConsultaInformacoesLoteResponse() {
        }
        
        public ConsultaInformacoesLoteResponse(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaInformacoesLoteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class ConsultaInformacoesLoteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetornoXML;
        
        public ConsultaInformacoesLoteResponseBody() {
        }
        
        public ConsultaInformacoesLoteResponseBody(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaCNPJRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaCNPJRequest", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaCNPJRequestBody Body;
        
        public ConsultaCNPJRequest() {
        }
        
        public ConsultaCNPJRequest(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaCNPJRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class ConsultaCNPJRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int VersaoSchema;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string MensagemXML;
        
        public ConsultaCNPJRequestBody() {
        }
        
        public ConsultaCNPJRequestBody(int VersaoSchema, string MensagemXML) {
            this.VersaoSchema = VersaoSchema;
            this.MensagemXML = MensagemXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaCNPJResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaCNPJResponse", Namespace="http://www.prefeitura.sp.gov.br/nfe", Order=0)]
        public SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaCNPJResponseBody Body;
        
        public ConsultaCNPJResponse() {
        }
        
        public ConsultaCNPJResponse(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaCNPJResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.prefeitura.sp.gov.br/nfe")]
    public partial class ConsultaCNPJResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RetornoXML;
        
        public ConsultaCNPJResponseBody() {
        }
        
        public ConsultaCNPJResponseBody(string RetornoXML) {
            this.RetornoXML = RetornoXML;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoteNFeSoapChannel : SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.LoteNFeSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoteNFeSoapClient : System.ServiceModel.ClientBase<SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.LoteNFeSoap>, SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.LoteNFeSoap {
        
        public LoteNFeSoapClient() {
        }
        
        public LoteNFeSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoteNFeSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoteNFeSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoteNFeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.EnvioRPSResponse EnvioRPS(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.EnvioRPSRequest request) {
            return base.Channel.EnvioRPS(request);
        }
        
        public SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.EnvioLoteRPSResponse EnvioLoteRPS(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.EnvioLoteRPSRequest request) {
            return base.Channel.EnvioLoteRPS(request);
        }
        
        public SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.TesteEnvioLoteRPSResponse TesteEnvioLoteRPS(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.TesteEnvioLoteRPSRequest request) {
            return base.Channel.TesteEnvioLoteRPS(request);
        }
        
        public SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.CancelamentoNFeResponse CancelamentoNFe(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.CancelamentoNFeRequest request) {
            return base.Channel.CancelamentoNFe(request);
        }
        
        public SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaNFeResponse ConsultaNFe(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaNFeRequest request) {
            return base.Channel.ConsultaNFe(request);
        }
        
        public SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaNFeRecebidasResponse ConsultaNFeRecebidas(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaNFeRecebidasRequest request) {
            return base.Channel.ConsultaNFeRecebidas(request);
        }
        
        public SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaNFeEmitidasResponse ConsultaNFeEmitidas(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaNFeEmitidasRequest request) {
            return base.Channel.ConsultaNFeEmitidas(request);
        }
        
        public SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaLoteResponse ConsultaLote(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaLoteRequest request) {
            return base.Channel.ConsultaLote(request);
        }
        
        public SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaInformacoesLoteResponse ConsultaInformacoesLote(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaInformacoesLoteRequest request) {
            return base.Channel.ConsultaInformacoesLote(request);
        }
        
        public SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaCNPJResponse ConsultaCNPJ(SoftFin.NFSePrefeituraSaoPaulo.NFePrefSP.ConsultaCNPJRequest request) {
            return base.Channel.ConsultaCNPJ(request);
        }
    }
}
