//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftFin.Sefaz.srwsNFeAutorizacao {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4", ConfigurationName="srwsNFeAutorizacao.NFeAutorizacao4Soap12")]
    public interface NFeAutorizacao4Soap12 {
        
        // CODEGEN: Generating message contract since the operation nfeAutorizacaoLote is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4/nfeAutorizacaoLote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoftFin.Sefaz.srwsNFeAutorizacao.nfeAutorizacaoLoteResponse nfeAutorizacaoLote(SoftFin.Sefaz.srwsNFeAutorizacao.nfeAutorizacaoLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4/nfeAutorizacaoLote", ReplyAction="*")]
        System.Threading.Tasks.Task<SoftFin.Sefaz.srwsNFeAutorizacao.nfeAutorizacaoLoteResponse> nfeAutorizacaoLoteAsync(SoftFin.Sefaz.srwsNFeAutorizacao.nfeAutorizacaoLoteRequest request);
        
        // CODEGEN: Generating message contract since the operation nfeAutorizacaoLoteZip is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4/nfeAutorizacaoLoteZip", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoftFin.Sefaz.srwsNFeAutorizacao.nfeAutorizacaoLoteZipResponse nfeAutorizacaoLoteZip(SoftFin.Sefaz.srwsNFeAutorizacao.nfeAutorizacaoLoteZipRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4/nfeAutorizacaoLoteZip", ReplyAction="*")]
        System.Threading.Tasks.Task<SoftFin.Sefaz.srwsNFeAutorizacao.nfeAutorizacaoLoteZipResponse> nfeAutorizacaoLoteZipAsync(SoftFin.Sefaz.srwsNFeAutorizacao.nfeAutorizacaoLoteZipRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeAutorizacaoLoteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4", Order=0)]
        public System.Xml.XmlNode nfeDadosMsg;
        
        public nfeAutorizacaoLoteRequest() {
        }
        
        public nfeAutorizacaoLoteRequest(System.Xml.XmlNode nfeDadosMsg) {
            this.nfeDadosMsg = nfeDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeAutorizacaoLoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4", Order=0)]
        public System.Xml.XmlNode nfeResultMsg;
        
        public nfeAutorizacaoLoteResponse() {
        }
        
        public nfeAutorizacaoLoteResponse(System.Xml.XmlNode nfeResultMsg) {
            this.nfeResultMsg = nfeResultMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeAutorizacaoLoteZipRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4", Order=0)]
        public string nfeDadosMsgZip;
        
        public nfeAutorizacaoLoteZipRequest() {
        }
        
        public nfeAutorizacaoLoteZipRequest(string nfeDadosMsgZip) {
            this.nfeDadosMsgZip = nfeDadosMsgZip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeAutorizacaoLoteZipResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeAutorizacao4", Order=0)]
        public System.Xml.XmlNode nfeResultMsg;
        
        public nfeAutorizacaoLoteZipResponse() {
        }
        
        public nfeAutorizacaoLoteZipResponse(System.Xml.XmlNode nfeResultMsg) {
            this.nfeResultMsg = nfeResultMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NFeAutorizacao4Soap12Channel : SoftFin.Sefaz.srwsNFeAutorizacao.NFeAutorizacao4Soap12, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NFeAutorizacao4Soap12Client : System.ServiceModel.ClientBase<SoftFin.Sefaz.srwsNFeAutorizacao.NFeAutorizacao4Soap12>, SoftFin.Sefaz.srwsNFeAutorizacao.NFeAutorizacao4Soap12 {
        
        public NFeAutorizacao4Soap12Client() {
        }
        
        public NFeAutorizacao4Soap12Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NFeAutorizacao4Soap12Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeAutorizacao4Soap12Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeAutorizacao4Soap12Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftFin.Sefaz.srwsNFeAutorizacao.nfeAutorizacaoLoteResponse SoftFin.Sefaz.srwsNFeAutorizacao.NFeAutorizacao4Soap12.nfeAutorizacaoLote(SoftFin.Sefaz.srwsNFeAutorizacao.nfeAutorizacaoLoteRequest request) {
            return base.Channel.nfeAutorizacaoLote(request);
        }
        
        public System.Xml.XmlNode nfeAutorizacaoLote(System.Xml.XmlNode nfeDadosMsg) {
            SoftFin.Sefaz.srwsNFeAutorizacao.nfeAutorizacaoLoteRequest inValue = new SoftFin.Sefaz.srwsNFeAutorizacao.nfeAutorizacaoLoteRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            SoftFin.Sefaz.srwsNFeAutorizacao.nfeAutorizacaoLoteResponse retVal = ((SoftFin.Sefaz.srwsNFeAutorizacao.NFeAutorizacao4Soap12)(this)).nfeAutorizacaoLote(inValue);
            return retVal.nfeResultMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftFin.Sefaz.srwsNFeAutorizacao.nfeAutorizacaoLoteResponse> SoftFin.Sefaz.srwsNFeAutorizacao.NFeAutorizacao4Soap12.nfeAutorizacaoLoteAsync(SoftFin.Sefaz.srwsNFeAutorizacao.nfeAutorizacaoLoteRequest request) {
            return base.Channel.nfeAutorizacaoLoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftFin.Sefaz.srwsNFeAutorizacao.nfeAutorizacaoLoteResponse> nfeAutorizacaoLoteAsync(System.Xml.XmlNode nfeDadosMsg) {
            SoftFin.Sefaz.srwsNFeAutorizacao.nfeAutorizacaoLoteRequest inValue = new SoftFin.Sefaz.srwsNFeAutorizacao.nfeAutorizacaoLoteRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            return ((SoftFin.Sefaz.srwsNFeAutorizacao.NFeAutorizacao4Soap12)(this)).nfeAutorizacaoLoteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftFin.Sefaz.srwsNFeAutorizacao.nfeAutorizacaoLoteZipResponse SoftFin.Sefaz.srwsNFeAutorizacao.NFeAutorizacao4Soap12.nfeAutorizacaoLoteZip(SoftFin.Sefaz.srwsNFeAutorizacao.nfeAutorizacaoLoteZipRequest request) {
            return base.Channel.nfeAutorizacaoLoteZip(request);
        }
        
        public System.Xml.XmlNode nfeAutorizacaoLoteZip(string nfeDadosMsgZip) {
            SoftFin.Sefaz.srwsNFeAutorizacao.nfeAutorizacaoLoteZipRequest inValue = new SoftFin.Sefaz.srwsNFeAutorizacao.nfeAutorizacaoLoteZipRequest();
            inValue.nfeDadosMsgZip = nfeDadosMsgZip;
            SoftFin.Sefaz.srwsNFeAutorizacao.nfeAutorizacaoLoteZipResponse retVal = ((SoftFin.Sefaz.srwsNFeAutorizacao.NFeAutorizacao4Soap12)(this)).nfeAutorizacaoLoteZip(inValue);
            return retVal.nfeResultMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftFin.Sefaz.srwsNFeAutorizacao.nfeAutorizacaoLoteZipResponse> SoftFin.Sefaz.srwsNFeAutorizacao.NFeAutorizacao4Soap12.nfeAutorizacaoLoteZipAsync(SoftFin.Sefaz.srwsNFeAutorizacao.nfeAutorizacaoLoteZipRequest request) {
            return base.Channel.nfeAutorizacaoLoteZipAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftFin.Sefaz.srwsNFeAutorizacao.nfeAutorizacaoLoteZipResponse> nfeAutorizacaoLoteZipAsync(string nfeDadosMsgZip) {
            SoftFin.Sefaz.srwsNFeAutorizacao.nfeAutorizacaoLoteZipRequest inValue = new SoftFin.Sefaz.srwsNFeAutorizacao.nfeAutorizacaoLoteZipRequest();
            inValue.nfeDadosMsgZip = nfeDadosMsgZip;
            return ((SoftFin.Sefaz.srwsNFeAutorizacao.NFeAutorizacao4Soap12)(this)).nfeAutorizacaoLoteZipAsync(inValue);
        }
    }
}
