//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftFin.Sefaz.srwsNFeRecepcaoEvento {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRecepcaoEvento4", ConfigurationName="srwsNFeRecepcaoEvento.NFeRecepcaoEvento4Soap12")]
    public interface NFeRecepcaoEvento4Soap12 {
        
        // CODEGEN: Generating message contract since the operation nfeRecepcaoEvento is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRecepcaoEvento4/nfeRecepcaoEvento", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SoftFin.Sefaz.srwsNFeRecepcaoEvento.nfeRecepcaoEventoResponse nfeRecepcaoEvento(SoftFin.Sefaz.srwsNFeRecepcaoEvento.nfeRecepcaoEventoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRecepcaoEvento4/nfeRecepcaoEvento", ReplyAction="*")]
        System.Threading.Tasks.Task<SoftFin.Sefaz.srwsNFeRecepcaoEvento.nfeRecepcaoEventoResponse> nfeRecepcaoEventoAsync(SoftFin.Sefaz.srwsNFeRecepcaoEvento.nfeRecepcaoEventoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeRecepcaoEventoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRecepcaoEvento4", Order=0)]
        public System.Xml.XmlNode nfeDadosMsg;
        
        public nfeRecepcaoEventoRequest() {
        }
        
        public nfeRecepcaoEventoRequest(System.Xml.XmlNode nfeDadosMsg) {
            this.nfeDadosMsg = nfeDadosMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class nfeRecepcaoEventoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.portalfiscal.inf.br/nfe/wsdl/NFeRecepcaoEvento4", Order=0)]
        public System.Xml.XmlNode nfeResultMsg;
        
        public nfeRecepcaoEventoResponse() {
        }
        
        public nfeRecepcaoEventoResponse(System.Xml.XmlNode nfeResultMsg) {
            this.nfeResultMsg = nfeResultMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NFeRecepcaoEvento4Soap12Channel : SoftFin.Sefaz.srwsNFeRecepcaoEvento.NFeRecepcaoEvento4Soap12, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NFeRecepcaoEvento4Soap12Client : System.ServiceModel.ClientBase<SoftFin.Sefaz.srwsNFeRecepcaoEvento.NFeRecepcaoEvento4Soap12>, SoftFin.Sefaz.srwsNFeRecepcaoEvento.NFeRecepcaoEvento4Soap12 {
        
        public NFeRecepcaoEvento4Soap12Client() {
        }
        
        public NFeRecepcaoEvento4Soap12Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NFeRecepcaoEvento4Soap12Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeRecepcaoEvento4Soap12Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NFeRecepcaoEvento4Soap12Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftFin.Sefaz.srwsNFeRecepcaoEvento.nfeRecepcaoEventoResponse SoftFin.Sefaz.srwsNFeRecepcaoEvento.NFeRecepcaoEvento4Soap12.nfeRecepcaoEvento(SoftFin.Sefaz.srwsNFeRecepcaoEvento.nfeRecepcaoEventoRequest request) {
            return base.Channel.nfeRecepcaoEvento(request);
        }
        
        public System.Xml.XmlNode nfeRecepcaoEvento(System.Xml.XmlNode nfeDadosMsg) {
            SoftFin.Sefaz.srwsNFeRecepcaoEvento.nfeRecepcaoEventoRequest inValue = new SoftFin.Sefaz.srwsNFeRecepcaoEvento.nfeRecepcaoEventoRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            SoftFin.Sefaz.srwsNFeRecepcaoEvento.nfeRecepcaoEventoResponse retVal = ((SoftFin.Sefaz.srwsNFeRecepcaoEvento.NFeRecepcaoEvento4Soap12)(this)).nfeRecepcaoEvento(inValue);
            return retVal.nfeResultMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftFin.Sefaz.srwsNFeRecepcaoEvento.nfeRecepcaoEventoResponse> SoftFin.Sefaz.srwsNFeRecepcaoEvento.NFeRecepcaoEvento4Soap12.nfeRecepcaoEventoAsync(SoftFin.Sefaz.srwsNFeRecepcaoEvento.nfeRecepcaoEventoRequest request) {
            return base.Channel.nfeRecepcaoEventoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftFin.Sefaz.srwsNFeRecepcaoEvento.nfeRecepcaoEventoResponse> nfeRecepcaoEventoAsync(System.Xml.XmlNode nfeDadosMsg) {
            SoftFin.Sefaz.srwsNFeRecepcaoEvento.nfeRecepcaoEventoRequest inValue = new SoftFin.Sefaz.srwsNFeRecepcaoEvento.nfeRecepcaoEventoRequest();
            inValue.nfeDadosMsg = nfeDadosMsg;
            return ((SoftFin.Sefaz.srwsNFeRecepcaoEvento.NFeRecepcaoEvento4Soap12)(this)).nfeRecepcaoEventoAsync(inValue);
        }
    }
}
