// <auto-generated />
namespace SoftFin.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class M04052018Ricardo01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(M04052018Ricardo01));
        
        string IMigrationMetadata.Id
        {
            get { return "201805041734581_M04052018Ricardo-01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
