// <auto-generated />
namespace SoftFin.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20181129Ricardo01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20181129Ricardo01));
        
        string IMigrationMetadata.Id
        {
            get { return "201811291808350_20181129Ricardo01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
