// <auto-generated />
namespace SoftFin.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Banco_TipoConta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Banco_TipoConta));
        
        string IMigrationMetadata.Id
        {
            get { return "201802281851070_Banco_TipoConta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
