// <auto-generated />
namespace SoftFin.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BM_Valida_Historico : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BM_Valida_Historico));
        
        string IMigrationMetadata.Id
        {
            get { return "201803122103175_BM_Valida_Historico"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
