// <auto-generated />
namespace SoftFin.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20190111Ricardo02 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20190111Ricardo02));
        
        string IMigrationMetadata.Id
        {
            get { return "201901111659564_20190111Ricardo02"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
