// <auto-generated />
namespace SoftFin.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20190201Ricardo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20190201Ricardo));
        
        string IMigrationMetadata.Id
        {
            get { return "201902011542495_20190201Ricardo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
