// <auto-generated />
namespace SoftFin.GestorProcessos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Full03 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Full03));
        
        string IMigrationMetadata.Id
        {
            get { return "201806261742532_Full03"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
